### ISSUE TITLE
SHA1 functions in DownloadManager conflict with functions from OpenSSL on Linux

### ISSUE THREAD

**Issue by Myaamori** [TypesettingTools/ffi-experiments#8]
They have the same name, and as DownloadManager ends up being dynamically linked to libcrypto.so, the OpenSSL function will be called instead, resulting in a segfault due to differing function signatures.

**Comment by CoffeeFlux** [comment]
Resolved in https://github.com/TypesettingTools/ffi-experiments/commit/76b1c55ea283e9e289741cef41e45d233fa65c5f
